name: "Bug Report"
description: "Report a bug to help us improve."
labels: ["bug"]
body:
  - type: "markdown"
    attributes:
      value: "Before submitting, please check for existing issues to avoid duplicates."
  
  - type: "textarea"
    id: "description"
    attributes:
      label: "Describe the Bug"
      description: "Provide a clear and concise description of what the bug is."
      placeholder: "A clear and concise description of what the bug is."
    validations:
      required: true
  
  - type: "textarea"
    id: "steps-to-reproduce"
    attributes:
      label: "Steps to Reproduce"
      description: "Provide an unambiguous set of steps to reproduce the bug."
      placeholder: "1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error"
    validations:
      required: true
  
  - type: "textarea"
    id: "expected-behavior"
    attributes:
      label: "Expected Behavior"
      description: "Describe what you expected to happen."
      placeholder: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  
  - type: "input"
    id: "os"
    attributes:
      label: "Operating System"
      description: "Provide details about your OS."
      placeholder: "e.g. Windows 10, macOS 14, Ubuntu 22.04"
    validations:
      required: true
  
  - type: "input"
    id: "browser"
    attributes:
      label: "Browser"
      description: "Provide details about the browser used."
      placeholder: "e.g. Chrome 120.0, Firefox 110.0, Edge 115.0"
    validations:
      required: true
  
  - type: "textarea"
    id: "additional-context"
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
      placeholder: "Any additional details or logs that might be relevant."
