name: "Feature Request"
description: "Suggest an idea for this project"
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: "Please provide details about your feature request below."

  - type: textarea
    id: problem-description
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is. Ex: I'm always frustrated when..."
      placeholder: "Explain the problem this feature would address."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
      placeholder: "Describe your ideal solution."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "List any alternative solutions."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Provide any extra details that might help."
    validations:
      required: false
