#!/usr/bin/env node

/*
Discord Extreme List - Discord's unbiased list.

Copyright (C) 2020 Cairo Mitchell-Acason, John Burke, Advaith Jagathesan

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

const redisFeaturing = require("../src/Util/Services/featuring.js");
const redisBans = require("../src/Util/Services/banned.js");
const redisBotCache = require("../src/Util/Services/botCaching.js");
const redisServerCache = require("../src/Util/Services/serverCaching.js");
const redisUserCache = require("../src/Util/Services/userCaching.js");

setTimeout(async () => {
    console.log("Init: Updating featured bots...");
    await redisFeaturing.updateFeaturedBots();
    console.log("Init: Updating featured servers...");
    await redisFeaturing.updateFeaturedServers();
    console.log("Init: Updating banlist...");
    await redisBans.updateBanlist();
    console.log("Init: Updating bot caches...")
    await redisBotCache.uploadBots();
    await redisBotCache.uploadAllBots();
    console.log("Init: Updating server caches...")
    await redisServerCache.uploadServers();
    await redisServerCache.uploadAllServers();
    console.log("Init: Updating the user cache...")
    await redisUserCache.uploadUsers();
    console.log("Init: Exiting...");
    process.exit(0);
}, 5000);
