#!/usr/bin/env node

/*
Discord Extreme List - Discord's unbiased list.

Copyright (C) 2020 Cairo Mitchell-Acason, John Burke, Advaith Jagathesan

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

const ioRedis = require("ioredis");
const cron = require("node-cron");

const settings = require("../settings.json");
const app = require("../app.js");
const discord = require("../src/Util/Services/discord.js");

const redisFeaturing = new ioRedis(settings.db.redis.featuring);
const redisBans = new ioRedis(settings.db.redis.bans);

async function updateFeaturedBots() {
    const bots = await app.db.collection("bots").aggregate({ $filter: { status: { approved: true, siteBot: false, archived: false } }, $limit: 3 }).toArray();
    redisFeaturing.set("bots", JSON.stringify(bots));
}

async function updateFeaturedServers() {
    const servers = await app.db.collection("servers").aggregate({ $limit: 3 }).toArray();
    redisFeaturing.set("servers", JSON.stringify(servers));
}

async function updateBanlist() {
    const bans = await discord.bot.guilds.get(settings.guild.main).getBans();
    console.log(bans)
    redisBans.set("bans", JSON.stringify(bans));
}

setTimeout(async () => {
    console.log("Init: Updating featured bots.");
    await updateFeaturedBots();
    console.log("Init: Updating featured servers.");
    await updateFeaturedServers();
    console.log("Init: Updating banlist.");
    await updateBanlist();
    console.log("Init: Exiting...");
    process.exit(0);
}, 5000);
