name: Add new issue/PR to project
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue/PR to the project board
        uses: actions/add-to-project@v2
        with:
          project-url: https://github.com/orgs/discordextremelist/projects/1
          github-token: ${{ secrets.DELLYBOT_SECRET }}
