name: Compile

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  node22:
    name: node v22 - tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: installs pnpm
        uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: '22.14.0'
          cache: 'pnpm'
      - name: dependencies
        run: pnpm i
      - name: settings
        run: cp settings.example.json settings.json
      - name: tsc
        uses: icrawl/action-tsc@v1.1.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
